### ISSUE TITLE
Git & GitHub |  Curso Extra

### ISSUE THREAD

**Issue by zoelner** [udacity/br-reactnd-issues#11]
Problema ao acessar link informado no curso, o mesmo informa que:

Você não tem permissão para acessar este programa Nanodegree. Sua inscrição foi pausada ou expirou?

Segue link:

https://classroom.udacity.com/nanodegrees/nd019/parts/34e90b9e-f2c4-4cbe-8dfa-46899ac0ab56

**Comment by thalescomp** [comment]
Olá Zoelner, bom me informar onde encontrou este link pra que eu possa verificar? Além disso, qual seu nome pra poder verificar sua conta?

Abs,
Thales

**Comment by thalescomp** [comment]
Encontrei sua conta! Conferi aqui e o curso de git & github está presente no seu Nanodegree. Agora só preciso mesmo do local onde você encontrou este link pra que eu possa colocar o link correto. :)

**Comment by zoelner** [comment]
@thalescomp não me recordo onde encontrei o problema tentei encontrar novamente, caso eu encontre alguma coisa e vá reportar vou me atentar a informar em qual aula ocorreu o problema

**Comment by thalescomp** [comment]
Beleza! Se encontrar então, me avise! Infelizmente não consegui encontrar aqui :/
