### ISSUE TITLE
Quiz aula 1.4 com defeito

### ISSUE THREAD

**Issue by romerorocha** [udacity/br-reactnd-issues#3]
No quiz onde a tarefa é colocar o "tijolo" correto para cada tipo ideal de estado, o tijolo azul aparentemente está com defeito. 
A resposta do quesito "input de formulário" é 'componente', mas ao colocar o componente azul e submeter, recebo o "tente novamente". Ao trocar pelo componente roxo, funciona.

**Comment by thalescomp** [comment]
Resolvido :+1:
