### ISSUE TITLE
Modais de envio de quiz sem tradução

### ISSUE THREAD

**Issue by adrianolsk** [udacity/br-reactnd-issues#4]
A maioria das mensagens após o envio de quiz está com a explicação em inglês.

**Comment by thalescomp** [comment]
@adrianolsk resposta dos quizes traduzidas! :+1:

As únicas respostas que não foram possíveis traduzir ainda são os quiz de programação, pois depende de uma atualização em uma feature da plataforma que está em desenvolvimento pela equipe de engenharia de US. Quando ficar pronto, em seguida iremos traduzir. Muito obrigado pela issue! 😃
