### ISSUE TITLE
ClassRoom Instability

### ISSUE THREAD

**Issue by mendoncaj** [udacity/br-reactnd-issues#6]
Hi there, I have been getting access React classroom but the web page loading is very slow. Maybe there is some maintenance right now.

**Comment by veronikabenkeser** [comment]
Hello! Are you still experiencing problems?

**Comment by mendoncaj** [comment]
Hi,

No. I don't everything is fine.

Tks.

On Thu, Nov 30, 2017 at 8:54 PM, Veronika Benkeser <notifications@github.com

**Comment by thalescomp** [comment]
Thanks for you feedback, @mendocaj! If you face any other instability, please feel free to reach us or to follow our Udacity Status: https://status.udacity.com/ :+1:
